# Generated by Django 2.1 on 2021-10-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('ALGORITHM_SEQUENCE_PK', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('ALGORITHM_NAME', models.CharField(max_length=100)),
                ('LIBRARY_NAME', models.CharField(max_length=100)),
                ('LIBRARY_VERSION', models.CharField(blank=True, max_length=50)),
                ('LIBRARY_DOCUMENT_URL', models.CharField(blank=True, max_length=200)),
                ('LIBRARY_OBJECT_NAME', models.CharField(max_length=50)),
                ('LIBRARY_FUNCTION_NAME', models.CharField(max_length=50)),
                ('LIBRARY_FUNCTION_DESCRIPTION', models.CharField(blank=True, max_length=500)),
                ('LIBRARY_FUNCTION_USAGE', models.CharField(max_length=50)),
                ('MODEL_PARAMETERS', models.TextField()),
                ('TRAIN_PARAMETERS', models.TextField()),
                ('SUPPORT_DATA_TYPE', models.CharField(blank=True, max_length=200)),
                ('CREATE_DATETIME', models.DateTimeField(auto_now_add=True)),
                ('WRITER', models.CharField(max_length=50)),
                ('USE_FLAG', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ALGORITHM',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BatchService',
            fields=[
                ('BATCH_SERVICE_SEQUENCE_PK', models.BigIntegerField(primary_key=True, serialize=False)),
                ('MODEL_COMMAND', models.TextField()),
                ('MODEL_SUMMARY', models.TextField()),
                ('PREPROCESSED_DATA_COMMAND', models.TextField()),
                ('PREPROCESSED_DATA_SUMMARY', models.TextField()),
                ('ORIGINAL_DATA_NAME', models.CharField(max_length=100)),
                ('MODEL_SANDBOX_SEQUENCE_FK1', models.BigIntegerField()),
                ('PREPROCESSED_DATA_SANDBOX_SEQUENCE_FK2', models.BigIntegerField()),
                ('ORIGINAL_DATA_SANDBOX_SEQUENCE_FK3', models.BigIntegerField()),
                ('CREATE_DATETIME', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BATCH_SERVICE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('identifier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('HEALTH_INFO', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'HEALTH_INFO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OriginalData',
            fields=[
                ('ORIGINAL_DATA_SEQUENCE_PK', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('NAME', models.CharField(max_length=100)),
                ('FILEPATH', models.CharField(max_length=300)),
                ('FILENAME', models.CharField(max_length=100)),
                ('EXTENSION', models.CharField(max_length=30)),
                ('CREATE_DATETIME', models.DateTimeField(auto_now_add=True)),
                ('COLUMNS', models.TextField()),
                ('STATISTICS', models.TextField()),
                ('SAMPLE_DATA', models.TextField()),
                ('AMOUNT', models.BigIntegerField()),
                ('DELETE_FLAG', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ORIGINAL_DATA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreprocessedData',
            fields=[
                ('PREPROCESSED_DATA_SEQUENCE_PK', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('COMMAND', models.TextField()),
                ('FILEPATH', models.CharField(blank=True, max_length=300)),
                ('FILENAME', models.CharField(blank=True, max_length=100)),
                ('SUMMARY', models.TextField(blank=True)),
                ('CREATE_DATETIME', models.DateTimeField(auto_now_add=True)),
                ('PROGRESS_STATE', models.CharField(default='standby', max_length=30)),
                ('PROGRESS_START_DATETIME', models.DateTimeField(blank=True, null=True)),
                ('PROGRESS_END_DATETIME', models.DateTimeField(blank=True, null=True)),
                ('COLUMNS', models.TextField()),
                ('STATISTICS', models.TextField()),
                ('SAMPLE_DATA', models.TextField()),
                ('AMOUNT', models.BigIntegerField()),
                ('DELETE_FLAG', models.BooleanField(default=False)),
                ('ORIGINAL_DATA_SEQUENCE_FK1', models.BigIntegerField()),
            ],
            options={
                'db_table': 'PREPROCESSED_DATA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreprocessFunction',
            fields=[
                ('PREPROCESS_FUNCTIONS_SEQUENCE_PK', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('PREPROCESS_FUNCTIONS_NAME', models.CharField(max_length=100)),
                ('LIBRARY_NAME', models.CharField(max_length=100)),
                ('LIBRARY_VERSION', models.CharField(blank=True, max_length=50)),
                ('LIBRARY_DOCUMENT_URL', models.CharField(blank=True, max_length=200)),
                ('LIBRARY_OBJECT_NAME', models.CharField(max_length=50)),
                ('LIBRARY_FUNCTION_NAME', models.CharField(max_length=50)),
                ('LIBRARY_FUNCTION_DESCRIPTION', models.CharField(blank=True, max_length=500)),
                ('LIBRARY_FUNCTION_USAGE', models.CharField(max_length=50)),
                ('PARAMETERS', models.TextField()),
                ('SUPPORT_DATA_TYPE', models.CharField(blank=True, max_length=200)),
                ('CREATE_DATETIME', models.DateTimeField(auto_now_add=True)),
                ('WRITER', models.CharField(max_length=50)),
                ('USE_FLAG', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'PREPROCESS_FUNCTION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrainInfo',
            fields=[
                ('MODEL_SEQUENCE_PK', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('COMMAND', models.TextField()),
                ('FILEPATH', models.CharField(blank=True, max_length=300)),
                ('FILENAME', models.CharField(blank=True, max_length=100)),
                ('TRAIN_SUMMARY', models.TextField(blank=True)),
                ('VALIDATION_SUMMARY', models.TextField(blank=True)),
                ('CREATE_DATETIME', models.DateTimeField(auto_now_add=True)),
                ('PROGRESS_STATE', models.CharField(default='standby', max_length=30)),
                ('PROGRESS_START_DATETIME', models.DateTimeField(blank=True, null=True)),
                ('PROGRESS_END_DATETIME', models.DateTimeField(blank=True, null=True)),
                ('LOAD_STATE', models.CharField(default='model_not_found', max_length=30)),
                ('DELETE_FLAG', models.BooleanField(default=False)),
                ('ORIGINAL_DATA_SEQUENCE_FK1', models.BigIntegerField()),
                ('PREPROCESSED_DATA_SEQUENCE_FK2', models.BigIntegerField(null=True)),
                ('JOB_ID', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'MODEL',
                'managed': True,
            },
        ),
    ]
